---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-adoption-profiling
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/lpanza/adoption-profiling-metrics.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
