apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

commonAnnotations:
  argocd.argoproj.io/sync-wave: "50"

resources:
#- operatorGroup.yaml
- subscription.yaml
