{
 "title": "Adoption Profiling Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node Name",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cluster:node_cpu:ratio_rate5m{cluster=\"\"}",
     "legendFormat": "Cluster CPU Utilization"
    }
   ]
  },
  {
   "title": "Cluster CPU Requests Commitment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{cluster=\"\"}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\",cluster=\"\"}) * 100",
     "legendFormat": "Cluster CPU Requests Commitment"
    }
   ]
  },
  {
   "title": "Cluster CPU Limits Commitment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_limits:sum{cluster=\"\"}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\",cluster=\"\"}) * 100",
     "legendFormat": "Cluster Limits Commitment"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - sum(:node_memory_MemAvailable_bytes:sum{cluster=\"\"}) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\",cluster=\"\"})) * 100",
     "legendFormat": "Cluster Memory Usage"
    }
   ]
  },
  {
   "title": "Cluster Memory Requests Commitment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum{cluster=\"\"}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\",cluster=\"\"}) * 100",
     "legendFormat": "Cluster Memory Requests Commitment"
    }
   ]
  },
  {
   "title": "Cluster Memory Limits Commitment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_limits:sum{cluster=\"\"}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\",cluster=\"\"}) * 100",
     "legendFormat": "Cluster Memory Limits Commitment"
    }
   ]
  },
  {
   "title": "Memory Utilization per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"\", node=\"$node\", resource=\"memory\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{cluster=\"\", node=\"$node\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"\", node=\"$node\", resource=\"cpu\"})",
     "legendFormat": "Node CPUs"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", node=\"$node\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "API Request Duration by Verb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{apiserver=\"kube-apiserver\",subresource!=\"log\",verb!~\"WATCH|WATCHLIST|PROXY\"}[5m])) by(verb,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Request Duration by Resource and Verb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(20, histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{apiserver=\"kube-apiserver\",subresource!=\"log\",verb!~\"WATCH|WATCHLIST|PROXY\"}[5m])) by(resource,verb,le)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unsuccessful API Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{apiserver=\"kube-apiserver\",code!~\"2..\"}[5m]))",
     "legendFormat": "Response not 2xx"
    }
   ]
  },
  {
   "title": "Failed % API calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{apiserver=\"kube-apiserver\",code=~\"[45]..\"}[5m]))*100/sum(rate(apiserver_request_total{apiserver=\"kube-apiserver\"}[5m]))\n",
     "legendFormat": "Failed Percentage"
    }
   ]
  },
  { "title": "ETCD Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "ETCD Members",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etcd_server_has_leader{job=\"etcd\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Leader Election per Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 43 },
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{job=\"etcd\"}[1d])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ETCD Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_request_duration_seconds_bucket[5m])) by(operation,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Traffic OUT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{job=\"etcd\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Client Traffic IN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{job=\"etcd\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=\"etcd\"}[5m])) by (pod, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETCD DataBase Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{job=\"etcd\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}