apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adoption-profiling

commonLabels:
  dashboards: adoption-profiling

resources:
- namespace.yaml
- clusterRoleBinding.yaml
- grafana.yaml
- grafanaDataSource.yaml
