apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adoption-profiling

commonLabels:
  dashboards: adoption-profiling

commonAnnotations:
  argocd.argoproj.io/sync-wave: "100"
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
- namespace.yaml
- clusterRoleBinding.yaml
- grafana.yaml
- grafanaDataSource.yaml
- grafanaDashboard.yaml
