apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: token-creator
  namespace: adoption-profiling
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: token-creator
subjects:
- kind: ServiceAccount
  name: token-creator
  namespace: adoption-profiling
