apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: token-creator
rules:
- apiGroups:
  - ""
  - batch
  resources:
  - serviceaccounts/token
  - secrets
  - jobs
  verbs:
  - create
  - list
  - get
  - patch
