---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: adoption-profiling-sa
    argocd.argoproj.io/sync-wave: "101"
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: adoption-profiling-sa
type: kubernetes.io/service-account-token
